.\" -*- nroff -*-
.\"
.\" ipcalc.1
.\"
.\" This program was written by
.\" Krischan Jodies <krischan@jodies.de>
.\"
.\" This manpage was created by:
.\" Nick Clifford <zaf@nrc.co.nz>
.\" 
.\" The author of the program retains copyrights to the program, however
.\" his manpage is Copyright (c) 2003   Nick Clifford 
.\"
.\" This program and this manpage is distributed under the terms of the 
.\" GNU General Public License. See COPYING for additional information.
.\"
.TH ipcalc 1 .\" "ipcalc Manual" "Jan 25, 2003"
.SH NAME
ipcalc - An IPv4 Netmask/broadcast/etc calculator
.SH SYNOPSIS
\fB ipcalc \fR [options] \fIADDRESS\fR[[/]\fINETMASK\fR] [\fINETMASK\fR]
.SH DESCRIPTION
\fBipcalc\fR takes an IPv4 address and netmask and calculates 
the resulting broadcast,
network, Cisco wildcard mask, and host range. By giving a second netmask, you
can design sub- and supernetworks. It is also intended to be a teaching tool
and presents the results as easy-to-understand binary values.
.TP
\fB--help\fR
Display help usage
.TP
\fB-n\fR, \fB--nocolor\fR
Don't display ANSI color codes
.TP
\fB-b\fR, \fB--nobinary\fR
Suppress the bitwise output
.TP
\fB-c\fR, \fB--class\fR
Just print bit-count-mask of given address
.TP
\fB-h\fR, \fB--html\fR
Display results as HTML
.TP
\fB-v\fR, \fB--version\fR
Print Version
.TP
\fB-s\fR, \fB--split\fR \fIn1\fR \fIn2\fR \fIn3\fR.
Split into networks of size n1, n2, n3
.TP
\fB-r\fR, \fB--range\fR
Deaggregate address range
.SH EXAMPLES
ipcalc 192.168.0.1/24
.PP
ipcalc 192.168.0.1/255.255.128.0
.PP
ipcalc 192.168.0.1 255.255.128.0 255.255.192.0
.PP
ipcalc 192.168.0.1 0.0.63.255
.PP
deaggregate address range
.RS
\fBipcalc <ADDRESS1> - <ADDRESS2>\fP
.RE
.PP
split network to subnets where a b c fits in
.RS
\fBipcalc <ADDRESS>/<NETMASK> -s a b c\fP
.RE
.SH AUTHOR
     Written by Krischan Jodies <krischan@jodies.de>
.SH "SEE ALSO"
.BR ipsc (1)
.BR gipsc (1)
.PP
The ipcalc website: http://jodies.de/ipcalc

